### ISSUE TITLE
这里。。为不在国内的主机设置国内加速源？

### ISSUE THREAD

**Issue by cxgreat2014** [lj2007331/oneinstack#104]
https://github.com/lj2007331/oneinstack/blob/991d7c98c2d57b4ef98e39af2b47b46fc1fb6398/include/python.sh#L81

应该改成`==`吧。。:笑cry:

**Comment by lj2007331** [comment]
已经修正，谢谢！
https://github.com/lj2007331/oneinstack/commit/db5a74180e1158e929e2b28e38f50bdf93ab1633
