### ISSUE TITLE
全新安装的LAMP，所有PHP文件访问即提示下载

### ISSUE THREAD

**Issue by zxz054321** [lj2007331/oneinstack#107]
Linux: Ubuntu 16.04
Apache: 2.4
MySQL: 5.6
PHP: 5.6

![screenshot](https://user-images.githubusercontent.com/7540550/33310480-b8ab9370-d45c-11e7-9cec-8a1e8db99060.png)

**Comment by zxz054321** [comment]
新版oneinstack才开始有的这个问题

**Comment by lj2007331** [comment]
service httpd restart 试试呢

**Comment by zxz054321** [comment]
也是这样，重启服务器也一样。不过安装LANP组合的话，打开phpmyadmin、phpinfo还是跟上图提示一样，但打开探针就正常显示页面

**Comment by lj2007331** [comment]
测试过没这个问题，方便的话，建议Email ip 密码排查。
