### ISSUE TITLE
如何更新oneinstack版本？

### ISSUE THREAD

**Issue by cxgreat2014** [lj2007331/oneinstack#108]
数月之前我在一台centos主机上下载安装了oneinstack，现在oneinstack已经更新很多次了，我该怎么升级本地的oneinstack呢？

**Comment by ivmm** [comment]
最近更新已经解决了

**Comment by lj2007331** [comment]
./upgrade.sh oneinstack

**Comment by YouthLin** [comment]
我是17年9月的版本，upgrade.sh  脚本好像不支持 更新 oneinstack,  这个版本该咋办？

**Comment by lj2007331** [comment]
下载覆盖，把dbrootpwd正确mysql密码写入options.conf
