### ISSUE TITLE
Ubuntu下openssl问题：/usr/local/openssl/lib/libcrypto.so.1.0.0: no version information available

### ISSUE THREAD

**Issue by guke1991** [lj2007331/oneinstack#110]
全新安装的Ubuntu16.04.3 64位server版
之后安装了oneinstack
接着执行：ssh-keygen -t ras -C "1217986946@qq.com"
结果如下：
guke@ubuntu:/data/wwwroot$ ssh-keygen -t ras -C "1217986946@qq.com"
ssh-keygen: /usr/local/openssl/lib/libcrypto.so.1.0.0: no version information available (required by ssh-keygen)
ssh-keygen: /usr/local/openssl/lib/libcrypto.so.1.0.0: no version information available (required by ssh-keygen)
unknown key type ras
本地vmware安装，感觉好像和https://github.com/lj2007331/oneinstack/issues/101 是一个问题。
之后删除了虚拟机重新创建，在不安装oneinstack的情况下执行ssh-kengen则正常。

**Comment by lj2007331** [comment]
不是ras，是rsa。
