### ISSUE TITLE
腾讯云COS备份设置失败

### ISSUE THREAD

**Issue by zrj766** [lj2007331/oneinstack#111]
dalao好，最近在设置备份的时候腾讯云COS的设置总是失败，在QQ群反馈和询问也一直没有得到反馈，只能来这里提问了。
设置了正确的地区、APP ID、SecretId、SecretKey、Bucket均设置失败，检查了多次输入的内容都是没问题的，反馈的信息都是
`input error! appid/secret_id/secret_key/region/bucket invalid`
感觉是脚本或者其他部分没有更新或者出错了，下载了最新版的Oninetack也没有解决。个人记得在半年前腾讯云COS备份设置是完全没问题的，最近新装了系统再设置就出错，试了几台服务器都是一样的问题，翻看官网的问答也有人问到这个问题，但是均没有任何解决方案，希望大佬可以查看一下这个问题，到底是什么原因。

**Comment by lj2007331** [comment]
方便的花，请私信群主，提供信息查看。
