### ISSUE TITLE
为什么装完oneinstack后，就连接不上ss了？

### ISSUE THREAD

**Issue by TGhoul** [lj2007331/oneinstack#113]
为了确认SS没有装错，我先安装了SS服务然后测试连接正常，然后再安装oneinstack，安装完成之后确实连接不上SS。请问作者是什么原因导致的？

**Comment by jayleco** [comment]
oneinstack应该跟你这个问题无关，你装完连不上看看是不是由于你服务器使用了安全策略，禁止了22端口之类的

**Comment by TGhoul** [comment]
没有的，我是先装完ss确认连接正常以后开始安装oneinstack。oneinstack安装是不是会启用防火墙策略？

**Comment by TGhoul** [comment]
不好意思，没有仔细看作者的网站，看到作者配置防火墙的教程了，谢谢🙏
