### ISSUE TITLE
安装redis后，使用service脚本启动会失败

### ISSUE THREAD

**Issue by mingmingbaibai** [lj2007331/oneinstack#120]
安装redis后，使用service脚本启动会失败，原因是pid文件权限问题，修改方法：使用超管用户 mkdir /var/run/redis && chown redis.redis /var/run/redis ，同时修改/usr/local/redis/conf/redis.conf的pid文件路径为/var/run/redis/6379.pid及/etc/init.d/redis-server的pid文件路径。再启动即可。

**Comment by lj2007331** [comment]
已经修复：https://github.com/lj2007331/oneinstack/commit/e97ff4ce73ad2f3da58e6407dc9b213d5edb8e42
