### ISSUE TITLE
能否取消编译时关闭PHP fileinfo

### ISSUE THREAD

**Issue by shulan-moe** [lj2007331/oneinstack#121]
Mediawiki-1.13.0安装更新需要fileinfo 提示缺失，经查是使用oneinstack安装时有--disable-fileinfo 参数，想请教为什么需要关闭fileinfo呢？能否添加选项选择是否关闭或者默认打开呢？谢谢！
--现已自行手动删除此参数解决问题。

**Comment by lj2007331** [comment]
./addons.sh 安装fileinfo即可
