### ISSUE TITLE
LAMP模式下，Apache启动失败

### ISSUE THREAD

**Issue by zrj766** [lj2007331/oneinstack#122]
新安装的LAMP环境，安装完成重启系统，发现Apache启动失败
`systemctl status httpd.service
● httpd.service - SYSV: Apache is a World Wide Web server. It is used to serve
   Loaded: loaded (/etc/init.d/httpd)
   Active: failed (Result: exit-code) since Mon 2017-12-18 18:18:06 CST; 6s ago
  Process: 4102 ExecStart=/etc/init.d/httpd start (code=exited, status=1/FAILURE)

Dec 18 18:18:06 localhost httpd[4102]: httpd: Syntax error on line 142 of /usr/local/apache/conf/httpd.conf: Cannot load...finish
Dec 18 18:18:06 localhost systemd[1]: httpd.service: control process exited, code=exited status=1
Dec 18 18:18:06 localhost systemd[1]: Failed to start SYSV: Apache is a World Wide Web server. It is used to serve.
Dec 18 18:18:06 localhost systemd[1]: Unit httpd.service entered failed state.
Hint: Some lines were ellipsized, use -l to show in full.
`
注释了142行也不行，连锁反应169行就废了，以前使用的时候没有遇到这个问题，不知道哪里有问题了，可以帮忙解决吗？

**Comment by lj2007331** [comment]
/usr/local/apache/conf/httpd.conf配置文件语法报错，改过什么地方吗？

**Comment by zrj766** [comment]
没有改，全新安装，安装后重启系统，直接打不开index.html那个页面

**Comment by lj2007331** [comment]
方便的话，请私信IP root密码看下。httpd.conf 语法报错。

**Comment by zrj766** [comment]
很奇怪，在阿里云的机器上是没有问题的，但是在Linode和LightSail上就出现了这种情况。。。

**Comment by zrj766** [comment]
又试了一下CloudCone的VPS，一样的问题，一样的组件安装，新安装完成后apache启动失败。难道是选择的软件源什么的有问题？已经发送给您一台测试机器信息到您的Gmail邮箱中，麻烦您有时间可以查看一下。

**Comment by lj2007331** [comment]
@zrj766 未收到

**Comment by lj2007331** [comment]
已经修正
