### ISSUE TITLE
tomcat安装问题

### ISSUE THREAD

**Issue by lovese** [lj2007331/oneinstack#126]
centos7.4运行install.sh不能安装tomcat，没有安装tomcat的选项，其他都能正常安装

**Comment by lj2007331** [comment]
Web 选择y

**Comment by lovese** [comment]
这么笨的错误我会犯吗？
![image](https://user-images.githubusercontent.com/13268438/34516604-70ad8714-f0b2-11e7-8008-f4d6087490f2.png)

**Comment by lj2007331** [comment]
q请下载oneinstack， lnmp不支持tomcat

**Comment by lovese** [comment]
tmux-2.6.tar.gzx下载失败
![image](https://user-images.githubusercontent.com/13268438/34550223-fccd72bc-f149-11e7-9274-bc3f6050654e.png)

**Comment by lovese** [comment]
好像是网络不稳定的原因

**Comment by lj2007331** [comment]
使用oneinstack-full吧
