### ISSUE TITLE
默认下载包含源码的ionCube版本过低

### ISSUE THREAD

**Issue by solarhell** [lj2007331/oneinstack#13]
希望可以增加一个检查机制，比如标注出源码包中的版本号？

**Comment by lj2007331** [comment]
已经重新下载 
http://downloads3.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64.tar.gz
http://downloads3.ioncube.com/loader_downloads/ioncube_loaders_lin_x86.tar.gz

**Comment by solarhell** [comment]
谢谢!
