### ISSUE TITLE
./include/get_public_ipaddr.py脚本不能正常执行导致其他安装脚本卡住

### ISSUE THREAD

**Issue by wind20180230** [lj2007331/oneinstack#130]
#!/usr/bin/env python
import re,urllib2
class Get_public_ip:
  def getip(self):
    try:
      myip = self.visit("http://ip.chinaz.com/getip.aspx")
    except:
      try:
        myip = self.visit("http://ipv4.icanhazip.com/")
      except:
        myip = "So sorry!!!"
    return myip
  def visit(self,url):
    opener = urllib2.urlopen(url)
    if url == opener.geturl():
      str = opener.read()
    return re.search('\d+\.\d+\.\d+\.\d+',str).group(0)

if __name__ == "__main__":
  getmyip = Get_public_ip()
  print getmyip.getip()

ip.chinaz.com/getip.aspx这个链接失效了，替换成ipv4.icanhazip.com运行就正常了

**Comment by lj2007331** [comment]
链接没有失效啊。

**Comment by wind20180230** [comment]
我在香港阿里云和日本亚马逊的服务器上都试了，都会卡住 。addon.sh   install.sh  都会卡住，换了链接就不卡了😂

2018-01-26 17:24 GMT+07:00 lj2007331 <notifications@github.com>:

**Comment by lj2007331** [comment]
./upgrade.sh oneinstack 即可
