### ISSUE TITLE
php-fpm not install

### ISSUE THREAD

**Issue by qbmiller** [lj2007331/oneinstack#132]
安装完后,找不到php-fpm
在install.log 中,也看不到任何fpm 日志....
php装的7.1

**Comment by qbmiller** [comment]
安装时候, apache nginx 都选了,  所以....可能就出了这么个问题...

**Comment by lj2007331** [comment]
LNMPA：安装Nginx、Apache，不安装Tomcat（该模式下，静态资源由Nginx处理，PHP由Apache处理，无php-fpm进程，php以模块形式加载在Apache中）
