### ISSUE TITLE
是否支持只备份website中的子目录

### ISSUE THREAD

**Issue by dongchengXie** [lj2007331/oneinstack#135]
请教一下，现在使用oneinstack中的backup，在填写需要备份的目录时，例如填写default/aaa，会说文件夹不存在，其实aaa是在default中的；填写default是没问题的。如何备份这个default中的子文件夹aaa呢？default在wwwroot中的

**Comment by lj2007331** [comment]
自动$wwwroot_dir(/data/wwwroot) 找目录
