### ISSUE TITLE
能否在addon.sh中添加一键安装waf的功能？

### ISSUE THREAD

**Issue by cxgreat2014** [lj2007331/oneinstack#136]
如题。。自己手动配挺麻烦。。

**Comment by baoang** [comment]
我连iptables都不会配。

我觉得对于一般小网站，没什么技术能力的人来说，被入侵的机会相对少一些，那么是否能够在安装过程中或装完之后，通过几个命令由oneinstack帮助把防火墙设置为全关（DROP），然后把22、21、80、443等常用端口打开放行，最多加上用户在安装过程中提交的几个特殊端口，这样安装完配置完防火墙基本就不用管了。

**Comment by lj2007331** [comment]
暂无

**Comment by lj2007331** [comment]
已加！
