### ISSUE TITLE
能否给用户提供选项是否开启防跨站？

### ISSUE THREAD

**Issue by cxgreat2014** [lj2007331/oneinstack#137]
未配置防跨站可能会造成安全问题。。如入侵主机上一个站点之后把主机上其他站点都干掉。。

https://segmentfault.com/a/1190000007942002

**Comment by cxgreat2014** [comment]
1000 Star完成~撒花✿✿ヽ(°▽°)ノ✿

**Comment by lj2007331** [comment]
网站根目录加.user.ini即可

**Comment by cxgreat2014** [comment]
但是lnmp在1.2版本之后是默认创建vhost就会生成.user.ini的。。emmm感觉两个特性不一致有点麻烦233
另外lnmp有一键安装apcu的功能。。emm希望oneinstack越做越好哈~/呲牙

**Comment by cxgreat2014** [comment]
刚才我看了一下。。貌似我在centos7上去年7月份用oneinstack搭建的环境没有apcu？discuz和mediawiki都提示找不到
