### ISSUE TITLE
centos6.5 安装失败

### ISSUE THREAD

**Issue by godofchina** [lj2007331/oneinstack#142]
virtual box + centos5.5 安装失败
openssl-1.0.2 install failed, Please contact the author!

c_zlib.c:25:19: error: zlib.h: No such file or directory

**Comment by lj2007331** [comment]
centos 5.5 还是6.5 ？

**Comment by huangguopeng** [comment]
应该要安装zlib-devel,
`yum install -y zlib zlib-devel`

**Comment by lj2007331** [comment]
默认有安装zlib-devel zlib动作！
