### ISSUE TITLE
[功能请求] 给备份功能加入全部数据库备份选项

### ISSUE THREAD

**Issue by TechCiel** [lj2007331/oneinstack#143]
在某些情况下需要对所有数据库进行备份，但是现有的只能选择现有的所有数据库。

本来想直接传入个 `--all-databases` 的，但是无奈OIS做了数据库存在性检查。

实现也不难，判断放 `--all-databases` 通过就好了。

提出这个建议，问一下 @lj2007331 的意见和大家的看法，请坐和放宽理性讨论，某个砸场子的就别来了。

**Comment by lj2007331** [comment]
数据库版本不一样，mysql建议不要覆盖，暂时不加！
