### ISSUE TITLE
[功能请求]可否考虑在编译php加入imap选择参数呢

### ISSUE THREAD

**Issue by AlphaBrock** [lj2007331/oneinstack#145]

**Comment by SeonMe** [comment]
Debian&Ubuntu :  apt-get install libc-client-dev
CentOS&Red Hat :  yum install libc-client-devel

###
1. You PHP Versions.

cd oneinstack/src/php-**versions**/ext/imap
/usr/local/php/bin/phpize

2.
./configure --with-php-config=/usr/local/php/bin/php-config --with-kerberos --with-imap-ssl && make && make install

3.

echo "extension=imap.so" > /usr/local/php/etc/php.d/imap.ini
service php-fpm restart

**Comment by lj2007331** [comment]
https://github.com/lj2007331/oneinstack/commit/e3138f9aa6910163e17ccce08a56a89edc3695a3
Try: ~/oneinstack/addons.sh
