### ISSUE TITLE
搬瓦工机器上安装会出现Exit code: 722999

### ISSUE THREAD

**Issue by baoang** [lj2007331/oneinstack#151]
在搬瓦工机器上安装过，又试了一台Vultr的机器，都是512MB的，搬瓦工机器失败，不但SSH无法连上，称连接拒绝，且通过后台管理面板中的ssh控制台（root shell basic）运行任何命令如pwd会出现提示
```
QEMU-KVM Agent is not running inside VE
Exit code: 722999
```
但在Vultr上并未出现。

第一次在搬瓦工上安装，是用的自动安装的页面生成的命令，lnmp的架构，并加上了memcached，出现以上错误后，感觉也许跟这个有关，就去掉了这个参数，不装它，用了如下的命令
```
wget -c http://mirrors.linuxeye.com/oneinstack-full.tar.gz && tar xzf oneinstack-full.tar.gz && ~/oneinstack/install.sh --nginx_option 1 --php_option 7 --phpcache_option 1 --phpmyadmin  --db_option 8 --dbinstallmethod 1 --dbrootpwd ywe5i2wf --pureftpd  --iptables  --ssh_port 22 --reboot 
```
但仍然出错，且从搬瓦工的管理界面上看，磁盘似乎不正常，表现为管理界面上的ram和swap这两栏没有了。

具体安装环境是这样的：搬瓦工与Vultr都用的512MB内存，都用的CentOS 6.x 32位系统。所不同的是，搬瓦工机器上有个它预先安装好的BBR。现在觉得，会不会跟这个有关？但是其它几个面板也都试过，宝塔、lnmp.org、Vesta等均无这个错误提示。

搜索了下，跟网上这里讲的一样（它有图）
http://dcfei.win/index.php/archives/184/

**Comment by lj2007331** [comment]
bbr不安装测试下？

**Comment by baoang** [comment]
多谢@lj2007331 ，应当不是BBR。我刚才在Centos 7 x86_64 bbr 上测试了一下，安装代码从`https://oneinstack.com/auto/`这里生成的。
```
wget -c http://mirrors.linuxeye.com/oneinstack-full.tar.gz && tar xzf oneinstack-full.tar.gz && ~/oneinstack/install.sh --nginx_option 1 --php_option 7 --phpcache_option 1 --phpmyadmin  --db_option 8 --dbinstallmethod 1 --dbrootpwd cbizvfin --pureftpd  --iptables  --ssh_port 28311 --reboot 
```
安装完在VPS的控制面板上仍然可以看到ram和swap两栏，且重新启动（没有手工重启，是安装代码里的那个自动重启）后，在SSH控制台或SSH连到主机上输入命令如pwd、ls等均正常，未出现之前722999的退出码了。

这次安装发现的不同是，搬瓦工的CentOS7BBR跟CentOS6BBR(32位，6的64位没试)中前者不带wget，后者有，这个软件本身应当没影响，现在猜，会不会是这两个版本搬瓦工提供的初始版其中有问题导致？
