### ISSUE TITLE
ubuntu16

### ISSUE THREAD

**Issue by Edinjohn** [lj2007331/oneinstack#153]
ubuntu16以root用户安装完后重启。
以非root用户运行 java -verson，nginx -v，mysql -uroot -p 都是有可以有返回/可以进入的。
但是切换到root(sudo -s 或者su root)，再运行，则提示
The program 'java' can be found in the following packages ...
nginx 和mysql相同，提示未找到该程序。
执行 source /etc/profile 后，一切正常
但是退出，切回普通用户，再切换到root用户时，又提示未安装应用了。。
（ubuntu默认不允许以root直接登录）

![tim 20180516173924](https://user-images.githubusercontent.com/16401814/40109516-1b375f3a-5930-11e8-8088-1c2e4d86d294.png)

搜索了一下oneinstack问答中心，https://oneinstack.com/question/6945/ 有人跟我遇到一样的情况了

**Comment by lj2007331** [comment]
什么问题呢？

**Comment by Edinjohn** [comment]
以 sudo 执行命令时会提示 command not found
