### ISSUE TITLE
Ubuntu 18.04编译memcached失败

### ISSUE THREAD

**Issue by 981213** [lj2007331/oneinstack#154]
Ubuntu 18.04 LTS使用GCC 7.3版本，编译libmemcached失败。

```
clients/memflush.cc:42:22: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
   if (opt_servers == false)
                      ^~~~~
clients/memflush.cc:51:24: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
     if (opt_servers == false)
                        ^~~~~
```
编译前需要打个补丁，参见：
https://bugs.launchpad.net/libmemcached/+bug/1663985
https://src.fedoraproject.org/cgit/rpms/libmemcached.git/plain/libmemcached-build.patch

**Comment by lj2007331** [comment]
https://github.com/lj2007331/oneinstack/commit/023378c8cfa321b735f424ef7d3f0ad5e2d2efac
