### ISSUE TITLE
WHMCS with SSL get Inf. Loop

### ISSUE THREAD

**Issue by brinsleyparagao** [lj2007331/oneinstack#155]
Hello...
When use WHMCS with SSL Certz and set in config the WHMCS to use HTTPS get infinity loops

So how to fix this ?

**Comment by lj2007331** [comment]
Can you print configuration file? example:/usr/local/nginx/conf/vhost/www.example.com.conf

**Comment by brinsleyparagao** [comment]
I use apache + nginx
