### ISSUE TITLE
CentOS 7.4 x64新系统安装OneInStack之后，fstab，mtab文件出现错误

### ISSUE THREAD

**Issue by arthurcn** [lj2007331/oneinstack#157]
./oneinstack/install.sh --nginx_option 1 --php_option 7 --phpcache_option 1 --php_extensions imagick --reboot

<img width="618" alt="2018-05-27 18 41 32" src="https://user-images.githubusercontent.com/12985838/40585146-0bc71122-61e0-11e8-907a-2cd98954020f.png">

<img width="1026" alt="2018-05-27 18 39 22" src="https://user-images.githubusercontent.com/12985838/40585137-e6ab8f44-61df-11e8-89fd-3eea6d1f8917.png">

安装oneinstack之前是好的，安装之后就这样了，

**Comment by lj2007331** [comment]
DebugFS 默认没打开。。。。一直使用centos7.4 ，刚刚测试过没这个现象啊！

**Comment by arthurcn** [comment]
腾讯云，重装系统再oneinstack，试了N遍，不管是自动还是手动，每次都是这样。只安装了nginx和php7.2

**Comment by arthurcn** [comment]
执行完第681行，没有问题，执行完682行 init_CentOS.sh，就出现这个问题了。

**Comment by arthurcn** [comment]
好像是系统本身的问题，只是因为添加了 /etc/profile.d/oneinstack.sh，让vi显示色彩样式了，才显示出了fstab的错误。
红色背景那行，是不是可以删除的啊

**Comment by lj2007331** [comment]
/etc/profile.d/oneinstack.sh 可以删除
