### ISSUE TITLE
lamp 模式下虚拟主机无法访问

### ISSUE THREAD

**Issue by ylqjgm** [lj2007331/oneinstack#158]
系统：CentOS7
Apache：apache 2.4
PHP：php 5.3
使用./vhost.sh添加一个域名，但是在访问时却无法访问，直接访问ip可以正常访问到默认页，就是虚拟主机无法访问。

**Comment by lj2007331** [comment]
什么报错？？？

**Comment by iBriBri** [comment]
试着重装Apache，编译可能出现问题。我是重装PHP和Apache解决的。
