### ISSUE TITLE
全自动安装lnmp方案未选OCP，但仍然装上了

### ISSUE THREAD

**Issue by baoang** [lj2007331/oneinstack#162]
`wget http://mirrors.linuxeye.com/oneinstack-full.tar.gz && tar xzf oneinstack-full.tar.gz && ./oneinstack/install.sh --nginx_option 1 --php_option 7 --phpmyadmin  --db_option 9 --dbinstallmethod 1 --dbrootpwd oneinstack --pureftpd  --iptables  --ssh_port 22 --reboot `

我用的是这样的安装lnmp的方案，也就是php的缓存、memecached等之类的都没装。但是安装完后一瞧，安装程序最后给出的信息里是这样的：

```
PHP install dir:                /usr/local/php
Opcache Control Panel URL:      http://ip/ocp.php
```

我打开Opcache CP的地址一瞧，还真有！
![Oneinstack安装自动模式](https://user-images.githubusercontent.com/17093525/41601215-6dc82f64-740a-11e8-9c21-7f519896a08b.png)
![Opcache Control Panel](https://user-images.githubusercontent.com/17093525/41601274-9ae55238-740a-11e8-90fd-e0add6a83543.png)

我的系统是Centos 7 x86_64 bbr(minimal)，内核是4.17.2-1.el7.elrepo.x86_64

**Comment by lj2007331** [comment]
Fix install phpcache_option: https://github.com/lj2007331/oneinstack/commit/2c54d2a350132203124f57341075611371646c8b

THX
