### ISSUE TITLE
Backup Configuration

### ISSUE THREAD

**Issue by brinsleyparagao** [lj2007331/oneinstack#166]
Hello...

When i try configurate the backup i give this error:

> Please select your backup destination:
>         1. Localhost
>         2. Remote host
>         3. Aliyun OSS
>         4. Qcloud COS
>         5. UPYUN
>         6. QINIU
> Please input a number:(Default 1 press Enter) 1
> 
> Please select your backup content:
>         1. Only Database
>         2. Only Website
>         3. Database and Website
> Please input a number:(Default 1 press Enter) 3
> 
> Please enter the directory for save the backup file:
> (Default directory: /data/backup):
> 
> Pleas enter a valid backup number of days:
> (Default days: 5):
> ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
> 
> Please enter one or more name for database, separate multiple database names with commas:
> (Default database: )

how to fix this?

**Comment by lj2007331** [comment]
You must write the correct mysql root password to options.conf dbrootpwd='You mysql root pwd'
