### ISSUE TITLE
是否可以使用原生systemd启动hhvm（就像启动其他服务一样）

### ISSUE THREAD

**Issue by minmemory** [lj2007331/oneinstack#168]
是否可以使用原生systemd启动hhvm（就像启动其他服务一样），而淘汰低效的supervisor呢，我觉得重复造轮子的意义已经不大了，supervisor可以做的几乎systemd都可以做，而且systemd是集成的系统服务

**Comment by minmemory** [comment]
[Unit]
Description=HipHop Virtual Machine

[Service]
ExecStart=/usr/bin/hhvm --mode server --user www --config /etc/hhvm/server.ini --config /etc/hhvm/php.ini --config /etc/hhvm/config.hdf
ExecStop=rm /var/run/hhvm.pid
PIDFile=/var/run/hhvm.pid

[Install]
WantedBy=multi-user.target

**Comment by lj2007331** [comment]
https://github.com/lj2007331/oneinstack/commit/ace6c3447d8c35d3f7ce9d3d0cb09d7235608d61
