### ISSUE TITLE
about arm server support.

### ISSUE THREAD

**Issue by Senrt** [lj2007331/oneinstack#170]
![](https://s1.ax1x.com/2018/07/25/PtK9IJ.jpg)

This is a ARM server. and system is Ubuntu Server Armhf 16.04 "Xenial Xerus" (32bits)

It has more than one system template.

![](https://s1.ax1x.com/2018/07/25/PtKlRI.png)

Its CPU is ARM Cortex A9 ARMv7. DDR3 2GB

I am not sure what information I still need to provide.

Is there a plan to support it? I can lend the server to you for debugging.

**Comment by lj2007331** [comment]
Try again
