### ISSUE TITLE
Let's Encrypt   dnsAPI 不通过

### ISSUE THREAD

**Issue by Sgenmi** [lj2007331/oneinstack#171]
./vhost dnsapi

~/.acme.sh/acme.sh --issue --dns dns_${DNS_PRO} -d ${domain} -d ${moredomain}
moredomain 不能为多域名 希望被修复

**Comment by lj2007331** [comment]
https://github.com/lj2007331/oneinstack/commit/13147ddc24743dc243f7f44108c367447429e833
