### ISSUE TITLE
防盗链 白名单重复

### ISSUE THREAD

**Issue by Sgenmi** [lj2007331/oneinstack#172]
场景，
  vhost.sh    
 更多域名里 增加 *.xxx.com 同时选择防盗链 
bug:  valid_referers none blocked *.xxx.com  xxx.com  *.xxx.com ;
valid_referers 白名单中，会有二个*.xxx.com  导致nginx -t报错。不能生成vhost

**Comment by lj2007331** [comment]
https://github.com/lj2007331/oneinstack/commit/e0d7b43be8616d257c8e4ac5040a130f137b4224
