### ISSUE TITLE
centos7 如何单独安装tomcat，而不强制安装jdk？

### ISSUE THREAD

**Issue by wangjia2016** [lj2007331/oneinstack#175]
![image](https://user-images.githubusercontent.com/16084076/44828372-269a3d80-ac4a-11e8-9ae3-28f0ff71cc61.png)
这样JDK必须要选择了

**Comment by lj2007331** [comment]
参考：https://oneinstack.com/auto ，如仅安装tomcat-8，执行：
～/oneinstack/install.sh --tomcat 2

**Comment by hastonewy** [comment]
还不如模块化 做成几个独立的sh 比如jdk.sh tomcat.sh

yeho <notifications@github.com> 于2018年8月30日周四 下午4:30写道：
