### ISSUE TITLE
issue about letsencrypt with apache 2.2 in ubuntu 14

### ISSUE THREAD

**Issue by johnfelipe** [lj2007331/oneinstack#177]
![snag-0069](https://user-images.githubusercontent.com/428820/47476564-aaa21900-d7e6-11e8-8b26-ef8c44360f0c.png)

and my dns is:

![snag-0070](https://user-images.githubusercontent.com/428820/47476584-c5748d80-d7e6-11e8-9a15-84c3b6456ac9.png)

how solve that?

**Comment by lj2007331** [comment]
Please try again...
