### ISSUE TITLE
ubuntu1810 安装完postgresql 不能开机启动

### ISSUE THREAD

**Issue by ptsa** [lj2007331/oneinstack#179]
ubuntu1810 安装完postgresql 不能开机启动
重启以后状态是 
root@u1810:~# service postgresql status
● postgresql.service - SYSV: PostgreSQL RDBMS
   Loaded: loaded (/etc/init.d/postgresql; generated)
   Active: inactive (dead)
     Docs: man:systemd-sysv-generator(8)

**Comment by ptsa** [comment]
删除原/etc/init.d/postgresql
新建了/etc/systemd/system/postgresql.service

[Unit]
Description=PostgreSQL database server
After=network.target
[Service]
Type=forking
User=postgres
Group=postgres
OOMScoreAdjust=-1000
Environment=PG_OOM_ADJUST_FILE=/proc/self/oom_score_adj
Environment=PG_OOM_ADJUST_VALUE=0
Environment=PGSTARTTIMEOUT=270
Environment=PGDATA=/data/pgsql
ExecStart=/usr/local/pgsql/bin/pg_ctl start -D ${PGDATA} -s -w -t ${PGSTARTTIMEOUT}
ExecStop=/usr/local/pgsql/bin/pg_ctl stop -D ${PGDATA} -s -m fast
ExecReload=/usr/local/pgsql/bin/pg_ctl reload -D ${PGDATA} -s
TimeoutSec=300

[Install]
WantedBy=multi-user.target


添加启动
systemctl daemon-reload
systemctl enable postgresql

**Comment by ptsa** [comment]
网上找的  希望能下次能直接改用systemd

**Comment by lj2007331** [comment]
已经调整：https://github.com/lj2007331/oneinstack/commit/7e7cfa8819968c365daeb980cda11af33cb29665
