### ISSUE TITLE
报告一个关于 ssl 的错误

### ISSUE THREAD

**Issue by cnyyk** [lj2007331/oneinstack#18]
当启用 SSL 后，WORDPRESS 不能正常工作。
原因在于：wordpress 的资源文件的链接，会在运行时自动输出 http 或者 https。

当在您的 lnmpa 组合上启用 ssl 并替换为 let'sencrypt 的 ssl 证书后，所有传递到 apache 的都是 http 连接了。见如下代码：

location @apache {
    proxy_pass http://127.0.0.1:88;
    include proxy.conf;
    }
location ~ .*\.(php|php5|cgi|pl)?$ {
    proxy_pass http://127.0.0.1:88;
    include proxy.conf;
    }

这样带来的问题是，https 的页面，有大量的由 wordpress 输出产生的 http 的 css、js、图片等的链接，导致页面显示错乱，浏览器提醒链接未能全部使用 ssl。

盼修复。

**Comment by cnyyk** [comment]
经研究发现，改正的方法很简单：
在 apache 的 vhost 对应文件，即<VirtualHost *:88>里面增加
SSLEngine on
SSLCertificateFile "/etc/letsencrypt/live/xxx.com/cert.pem"
SSLCertificateKeyFile "/etc/letsencrypt/xxx.com/privkey.pem"

就可以正常工作了。

建议 @lj2007331修改下脚本代码，当启用了 ssl 后，同时在 apache 的配置文件增加对应配置行。

**Comment by lj2007331** [comment]
已修复！
