### ISSUE TITLE
什么样的情况下会请求OneinStack的网站

### ISSUE THREAD

**Issue by sunsan05** [lj2007331/oneinstack#180]
如图：
![_15416464129553](https://user-images.githubusercontent.com/14139451/48175609-c01b5500-e347-11e8-9526-0da5b076aa9c.png)
最近一段时间统计下来一共访问这两个站这么几次。

**Comment by lj2007331** [comment]
安装过程或者升级时候才会请求oneinstack网站，其余没有

**Comment by sunsan05** [comment]
好的，感谢~
