### ISSUE TITLE
ubuntu 16.04 64位下 nginx 命令行问题。

### ISSUE THREAD

**Issue by pfdiy** [lj2007331/oneinstack#187]
第一次安装重启后，首先我安装了 python3-pip，pipenv，创建了flask环境，然后配置完毕后，添加域名 选择的 自有ssl证书。重启nginx的时候发现 service nginx restart 提示：
```bash
nginx: unrecognized service
```
重启一下机器可以使用，但是输入service nginx 的时候 不会提示其他命令。
虽然好用了 但是 nginx -t 会出现
![Image of Yaktocat](https://i.loli.net/2018/12/04/5c068fabc2d9e.png)

**Comment by lj2007331** [comment]
`echo $PATH #看下path变量`
或者：
`grep PATH /etc/profile`

**Comment by pfdiy** [comment]
> `echo $PATH #看下path变量`
> 或者：
> `grep PATH /etc/profile`

'''
export PATH=/usr/local/nginx/sbin:/usr/local/mysql/bin:$PATH
'''

**Comment by lj2007331** [comment]
echo $PATH 看看！，不应该有问题啊

**Comment by lj2007331** [comment]
从一般用户切换到root，请用 `sudo su -` 这样把环境变量带过去

**Comment by pfdiy** [comment]
我发现，好像是系统模版的问题，搬瓦工就一点问题都没有，另一个virmach就不行，貌似是这样的。

**Comment by pfdiy** [comment]
> 从一般用户切换到root，请用 `sudo su -` 这样把环境变量带过去

我发现，好像是系统模版的问题，搬瓦工就一点问题都没有，另一个virmach就不行，貌似是这样的。
