### ISSUE TITLE
可以添加postgresQL数据库不？

### ISSUE THREAD

**Issue by lchjczw** [lj2007331/oneinstack#19]

**Comment by pcwuyu** [comment]
同问

**Comment by Kumhy** [comment]
这个需求应该比较多

**Comment by guke1991** [comment]
支持

**Comment by lchjczw** [comment]
什么时候新增的这个数据库，说明里面没有呢

**Comment by lj2007331** [comment]
@lchjczw @pcwuyu @Kumhy @guke1991 @lchjczw 已经支持：https://github.com/lj2007331/oneinstack/commit/86a0d5dfc2bcc12264156d1f8f7b01b92988ca19
