### ISSUE TITLE
建议支持无人值守

### ISSUE THREAD

**Issue by zxz054321** [lj2007331/oneinstack#23]
目前的安装过程需要用户交互确认安装哪些选项，如果能无人值守静默安装，那就很方便进行集群自动化部署了

**Comment by kaneawk** [comment]
Good idea. But need to modify the install.sh read an auto-install configuration file, it's a lot of trouble.

**Comment by zxz054321** [comment]
Maybe we can use scripts( written by Python or something else) to read an auto-install configuration file. It's easier than modifying the install.sh.

**Comment by duanzhanling** [comment]
建议还是shell脚本

**Comment by zxz054321** [comment]
@duanzhanling 可以shell脚本包办一切的话再好不过

**Comment by lchjczw** [comment]
新增一份默认配置文件，开启静默安装的话，就直接按照默认配置安装

**Comment by bao3** [comment]
非常需要静默安装，现在的交互过程太痛苦了。

**Comment by ivmm** [comment]
可以试试这样

```
./install.sh -web -y httpd -n nginx -y tengine -n openresty -n tomcat -n php -5.7 mysql -5.7 
```

这样来，或许会好些

**Comment by kchum** [comment]
同非常需要~

**Comment by KiritoMiao** [comment]
魔改下install.sh吧，还是比较简单的

**Comment by cxgreat2014** [comment]
同需要+1

**Comment by lj2007331** [comment]
已经支持：https://github.com/lj2007331/oneinstack/commit/258febdeb3a384957a1f4dfe613b6534eada054e

**Comment by baoang** [comment]
在站长的网站上看到现在可以支持无人值守安装了，但是如果能有一个更方便的比如VestaCP那样的自动值守安装命令生成工具就更好了，lnmp.org现在有一个网页可以这样做。
