### ISSUE TITLE
lnmpa 组合下的 tengine concat 失效

### ISSUE THREAD

**Issue by cnyyk** [lj2007331/oneinstack#24]
惯用 lnmpa 组合，tengine 2.1.2 + apache 2.4。
默认安装下，nginx shared 方式编译了 对应的 so 模块，且 nginx.conf 已动态载入了 ngx_http_concat_module.so 模块
nginx -l 能看到

```
ngx_http_concat_module:`
    concat
    concat_max_files
    concat_unique
    concat_types
    concat_delimiter
    concat_ignore_file_error
```

在实际使用中，nginx 的 vhost 的 conf，在 location / 目录配置了 concat on。
但访问的时候，abc.com/??static/a.css,static/b.css，会被跳转到 apache 处理。
日志如下：

```
127.0.0.1 139.196.128.178 - - [21/Jun/2016:14:39:33 +0800] "GET /??static/a.css,static/b.css HTTP/1.0" 301 -
127.0.0.1 101.200.101.63 - - [21/Jun/2016:14:39:34 +0800] "GET /?static/a_css,static/b_css HTTP/1.0" 200 64043
```

CURL 的结果如下：

```
curl -I http://abc.com/??static/a.css,static/b.css

HTTP/1.1 301 Moved Permanently
Server: Tengine
Content-Type: text/html; charset=UTF-8
Content-Length: 0
Connection: keep-alive
Date: Tue, 21 Jun 2016 06:44:20 GMT
Location: http://abc.com/?static/a_css,static/b_css
Strict-Transport-Security: max-age=15768000
```

经过这样转换后，??变成了一个页面的参数，concat 无法起作用。

检查后发现可能的问题是 nginx 的 vhost conf 文件里面的如下：

```
location / {
	concat on;
	try_files $uri @apache;
}
```

尽管开启了 concat，但是仍然将 ?? 的请求转发到了 apache，从而导致 concat 失效。

鉴于上述描述，如何在 lnmpa 组合下，将 concat 开启，还请 @lj2007331 指导为谢。

**Comment by cnyyk** [comment]
请问这个是 tengine 的问题？还是配置文件不正确导致的？

还请 @lj2007331 指导为谢

**Comment by lj2007331** [comment]
@cnyyk 配置文件问题，请不要用apache试试
