### ISSUE TITLE
建议将所有命令脚本添加到环境变量里面，或者复制一份到/bin目录，这样可以在任何终端直接操作

### ISSUE THREAD

**Issue by lchjczw** [lj2007331/oneinstack#25]
现在添加虚拟主机，ftp等，每次需要切换到对应的目录实在有点麻烦
之前有个lnmp的安装包他们的命令就是加入环境变量了的

lnmp vhost add
lnmp restart 所有服务重启
lnmp nginx restart 只有nginx重启
等等`````

**Comment by lj2007331** [comment]
不会这样加，谁没事重启一遍所有服务，中断应用，不能养成这个习惯

**Comment by lchjczw** [comment]
nginx,mysql,php才三个服务，只是为了方便，现在每次切换到工作目录，才能操作，这个确实麻烦
