### ISSUE TITLE
建议添加MongoDB

### ISSUE THREAD

**Issue by zxz054321** [lj2007331/oneinstack#27]
MongoDB越来越流行，与PHP的配合度也越来越好，不少需求都很适合用MongoDB做。如果oneinstack支持MongoDB了，会方便很多

**Comment by wkii** [comment]
Mongodb扩展有两个。针对PHP的不同版本。7以上用一个，7以下用一个。
另外，我们常用的扩展有以一几个：
memcached(不再用memcache，不过考虑通用性，两个都加也好)
Imagick
Redis
Mongodb
Opcache
常用有这几个足够了。
希望作者可以考虑把没有的加上。

**Comment by zxz054321** [comment]
貌似除了MongoDB  楼上 @wkii 提到的都已经有了

**Comment by lchjczw** [comment]
建议加上

**Comment by helloxz** [comment]
MongoDB是二进制版本的，手动安装也不难吧。

**Comment by lj2007331** [comment]
已经加上：https://github.com/lj2007331/oneinstack/commit/fd44fa2f7739f507c53c29a1cdd833cd36cab747
