### ISSUE TITLE
能不能别修改 CentOS7的防火墙？！！！！！

### ISSUE THREAD

**Issue by fenghuilee** [lj2007331/oneinstack#28]
安装了，发现本来配置好的 Firewall 被改掉了，变成iptables，我了个去，流氓

**Comment by fenghuilee** [comment]
难道你比我更了解我的服务器的防火墙配置？

**Comment by lj2007331** [comment]
自己修改 https://github.com/lj2007331/oneinstack/blob/master/include/init_CentOS.sh

**Comment by fenghuilee** [comment]
好歹你也要让用户选择是否替换你的iptables，别让相信你的人失望啊，这脚本是会用在线上的服务器的，firewall都配置好了

**Comment by fenghuilee** [comment]
从ezhttp，转过来支持oneinstack

**Comment by lj2007331** [comment]
(⊙﹏⊙), 先安装再直接改防火墙，我不能照顾到每个人或每个需求

**Comment by fenghuilee** [comment]
不是啊，你在第一部输入 SSH 端口就可以询问一下是不是可以修改用户的防火墙设置不就行了，你这是强制修改了用户防火墙设置了，

**Comment by fenghuilee** [comment]
就跟你询问用户要不要安装web server不是一样的道理吗？！

**Comment by lj2007331** [comment]
太多选择用户会搞不懂，既然你会，可以自己改，不可能照顾所有用户，只能取舍

**Comment by wkii** [comment]
订阅了通知。就看你俩聊了。哈。
坦白的说，我用于生产服务器的， 也没有直接使用这个脚本。虽然我也提过意见，并且作者也确实按我的意见优化了，只是命名跟我提的意见不怎么一致，我这人又有强迫症。哈。
这些shell脚本也不复杂。你可以在拿到包以后，简单改一下。这东西确实不可能兼顾所有人。

**Comment by fenghuilee** [comment]
我现在在改init_CentOS配置

**Comment by fenghuilee** [comment]
我发现脚本里的madb 10.1.15一直下载不了，全是404啦

**Comment by lj2007331** [comment]
已经修正，官方最近比较坑 发布10.1.15 搞2天又撤销了。。
参考：https://mariadb.com/kb/en/mariadb/mariadb-10115-release-notes/
MariaDB-10.1.15 was never released, the next release after 10.1.14 is 10.1.16

**Comment by fenghuilee** [comment]
果然是个大坑，还把下载包去掉了

**Comment by wangjia2016** [comment]
现在还会替换firewall吗？
如果安装的时候，选择不启用IPtable是，是什么结果？
