### ISSUE TITLE
如何在已经安装了服务后，再次安装某些服务，比如Memcache

### ISSUE THREAD

**Issue by Brave-Cheng** [lj2007331/oneinstack#3]
我已经安装了PHP + NGINX + MYSQL ，现在想再次安装Memcache。请问应该如何执行操作？

**Comment by yumiao** [comment]
直接进入目录 ./install.sh 
脚本里面有判断目录是否存在的,如果存在对应的目录(根据那个options.conf)则跳过~

**Comment by lj2007331** [comment]
楼上正解
