### ISSUE TITLE
再提个建议哦，建议说明jdk的版本类型

### ISSUE THREAD

**Issue by duanzhanling** [lj2007331/oneinstack#36]
再提个建议哦，建议说明jdk的版本类型

我安装完毕jdk后，经过对比才发现是sunjdk，建议把这个在说明文档中写清楚哦。当然sunjdk刚好是符合我们应用的要求的。

**Comment by lj2007331** [comment]
jdk默认就是oracle jdk ，其余是另外名字。如openjdk，这个很好区别吧

**Comment by duanzhanling** [comment]
@lj2007331 嗯 是的 不好意思哦 可能我没有看仔细
非常感谢
