### ISSUE TITLE
percona xtrabackup or mydumper or myloader adding request

### ISSUE THREAD

**Issue by wetlyrics** [lj2007331/oneinstack#39]
mysqldump is unable for backing up large db like 200GB or 300gb
can't dump all data from the db.
is it possible add mydumper for backup and for restore myloader??
or auto configure mysqldump for dumping extra large db??
i did mysqldump adding max_allowed_packet = 500M both server and mysqldump block
and using:
mysqldump -u USER -pPASS --single-transaction --quick --lock-tables=false TABLE | gzip > TABLE.gz

for reference:
mydumper..
# !/bin/sh

DIR_BACKUP=/backup-directory
DB_NAME=database_name
DB_USER=user
DB_PASS=password

DOW=`date "+%a"`
DB_DUMP=$DIR_BACKUP/dbdump.$DB_NAME.$DOW

mydumper \
  --database=$DB_NAME \
  --host=$DB_HOST \
  --user=$DB_USER \
  --password=$DB_PASS \
  --outputdir=$DB_DUMP \
  --rows=500000 \
  --compress \
  --build-empty-files \
  --threads=2 \
  --compress-protocol

myloader:
myloader \
  --database=$DB_NAME \
  --directory=$DB_DUMP \
  --queries-per-transaction=50000 \
  --threads=6 \
  --compress-protocol \
  --verbose=3

**Comment by lj2007331** [comment]
You can install percona
