### ISSUE TITLE
建议加上LibreSSL以及BoringSSL以及OpenSSL-Patch选项

### ISSUE THREAD

**Issue by FlyGoat** [lj2007331/oneinstack#4]
建议加上LibreSSL以及BoringSSL以及OpenSSL-Patch选项。
现在OpenSSL不支持新的算法也越来越不安全了。
希望加上这些选项以便让他变得更个性化。
因为动不了Mirror所以没有Pull requests。
实现可以看这篇文章：https://neveta.com/technote/nginx-webserver-installation-and-optimization.html

**Comment by lj2007331** [comment]
暂时不添加。
