### ISSUE TITLE
希望下一个版本增加alisql作为数据库的可选项

### ISSUE THREAD

**Issue by hastonewy** [lj2007331/oneinstack#42]
如题

**Comment by lj2007331** [comment]
地址多少？

**Comment by hastonewy** [comment]
alisql尚未开源 下面这款是微信版的mysql也有集成的价值
https://github.com/tencent-wechat/phxsql

**Comment by fineinter** [comment]
阿里那么多烂尾的开源。看看Tengine就有点郁闷了

**Comment by vForce825** [comment]
AliSQL：https://github.com/alibaba/AliSQL
希望可以集成，谢谢

**Comment by lj2007331** [comment]
已经提交 https://github.com/lj2007331/oneinstack/commit/264406564ea27ae09da809ab3cd837f17fb1b372
测试请用链接：http://mirrors.linuxeye.com/oneinstack-full-beta.tar.gz

**Comment by lj2007331** [comment]
已经提交 https://github.com/lj2007331/oneinstack/commit/264406564ea27ae09da809ab3cd837f17fb1b372
测试请用链接：http://mirrors.linuxeye.com/oneinstack-full-beta.tar.gz

**Comment by lj2007331** [comment]
已经提交 https://github.com/lj2007331/oneinstack/commit/264406564ea27ae09da809ab3cd837f17fb1b372
测试请用链接：http://mirrors.linuxeye.com/oneinstack-full-beta.tar.gz

**Comment by lj2007331** [comment]
已经提交 https://github.com/lj2007331/oneinstack/commit/264406564ea27ae09da809ab3cd837f17fb1b372
测试请用链接：http://mirrors.linuxeye.com/oneinstack-full-beta.tar.gz

**Comment by lj2007331** [comment]
已经提交 https://github.com/lj2007331/oneinstack/commit/264406564ea27ae09da809ab3cd837f17fb1b372
测试请用链接：http://mirrors.linuxeye.com/oneinstack-full-beta.tar.gz

**Comment by lj2007331** [comment]
已经提交 https://github.com/lj2007331/oneinstack/commit/264406564ea27ae09da809ab3cd837f17fb1b372
测试请用链接：http://mirrors.linuxeye.com/oneinstack-full-beta.tar.gz
