### ISSUE TITLE
Percona 5.7 二进制安装有问题

### ISSUE THREAD

**Issue by ivmm** [lj2007331/oneinstack#46]
Percona-Server-5.7.14-7-Linux.x86_64.ssl100.tar.gz

在full 包解压后的 src 下 只有5.5和5.6，没有5.7. 但是安装的时候判断的是已经存在该文件，然后就导致安装失败了

**Comment by lj2007331** [comment]
操作系统版本多少？

**Comment by ivmm** [comment]
@lj2007331  Debian8.6 阿里云的那个 64bit
