### ISSUE TITLE
pcre版本引用错误导致tengine升级失败

### ISSUE THREAD

**Issue by cnyyk** [lj2007331/oneinstack#47]
`Configuration summary
  + using PCRE library: ../pcre-8.38
  + using system OpenSSL library
  + md5: using OpenSSL library
  + sha1: using OpenSSL library
  + using system zlib library
  + using system jemalloc library

  nginx path prefix: "/usr/local/tengine"
  nginx binary file: "/usr/local/tengine/sbin/nginx"
  nginx configuration prefix: "/usr/local/tengine/conf"
  nginx configuration file: "/usr/local/tengine/conf/nginx.conf"
  nginx pid file: "/usr/local/tengine/logs/nginx.pid"
  nginx error log file: "/usr/local/tengine/logs/error.log"
  nginx http access log file: "/usr/local/tengine/logs/access.log"
  nginx http client request body temporary files: "client_body_temp"
  nginx dso module path: "/usr/local/tengine/modules/"
  nginx http proxy temporary files: "proxy_temp"
  nginx http fastcgi temporary files: "fastcgi_temp"
  nginx http uwsgi temporary files: "uwsgi_temp"
  nginx http scgi temporary files: "scgi_temp"

make -f objs/Makefile
make[1]: Entering directory /root/oneinstack-github/src/tengine-2.1.2'

cd ../pcre-8.38 \  // <== 实际上应该是cd ../pcre-8.39

&& if [ -f Makefile ]; then make distclean; fi \
&& CC="cc" CFLAGS="-O2 -fomit-frame-pointer -pipe " \
./configure --disable-shared  --enable-jit
/bin/sh: line 0: cd: ../pcre-8.38: No such file or directory
make[1]: *** [../pcre-8.38/Makefile] Error 1
make[1]: Leaving directory /root/oneinstack-github/src/tengine-2.1.2'
make: *** [build] Error 2
Upgrade Tengine failed! 
`

<img width="545" alt="qq20161004-0 2x" src="https://cloud.githubusercontent.com/assets/275233/19062317/af84ea52-8a2b-11e6-8393-aa19ad8d4686.png">

**Comment by kaneawk** [comment]
Please use lastest oneinstack to upgrade your tengine.

**Comment by lj2007331** [comment]
tengine依赖原来的pcre版本，重新下载oneinstack后，src目录下没有pcre-8.38版本，只有pcre-8.39版本

**Comment by cnyyk** [comment]
是的，我已经使用的最新的github版本。升级之前已经进行过 git pull --all并提示已经最新。
