### ISSUE TITLE
nginx 添加mp4模块

### ISSUE THREAD

**Issue by woniu369** [lj2007331/oneinstack#48]
https://github.com/lj2007331/oneinstack/blob/master/include/nginx.sh#L38

flv已经支持了,把mp4也添加上吧. 

> --with-http_flv_module --with-http_mp4_module

**Comment by lj2007331** [comment]
options.conf 增加参数：nginx_modules_options='' ，写进去即可
https://github.com/lj2007331/oneinstack/commit/3f2f13aef896f39e95eb6fb67072ebf4b22f38a9
