### ISSUE TITLE
关于upgrade_yn

### ISSUE THREAD

**Issue by yashun** [lj2007331/oneinstack#5]
在最新的版本中，这个在实际情况中是没有执行的，可能作者疏忽了，upgrade_yn在执行中一直为空，导致init文件的yum -y upgrade是没有执行的。
另外一个关于php的，建议作者加上intl和xls这两个，请作者原谅我自己在脚本中更改了，以供自己实际需求使用。
nginx也是如此，自己做了更改，添加了许多新的库。

**Comment by lj2007331** [comment]
不建议更新操作系统，会导致问题，比如编译某些模块不能通过
--enable-intl --with-xsl 这两个模块测试过后加上，
nginx还是自己改吧
