### ISSUE TITLE
mysql 5.7的备用下载地址是5.6版本

### ISSUE THREAD

**Issue by jackytang** [lj2007331/oneinstack#50]
if [ "$(../include/check_port.py mirrors.tuna.tsinghua.edu.cn 443)" == 'True' ]; then
  DOWN_ADDR_MYSQL=https://mirrors.tuna.tsinghua.edu.cn/mysql/downloads/MySQL-5.7
else
  DOWN_ADDR_MYSQL=http://mirrors.sohu.com/mysql/MySQL-5.6
  DOWN_ADDR_MYSQL_BK=${DOWN_ADDR_MYSQL}
fi

**Comment by lj2007331** [comment]
fix：https://github.com/lj2007331/oneinstack/commit/42a7c74f37ddbc173da25c5388384f39219f61b9
