### ISSUE TITLE
1.4版本Tomcat 8不自动解压war包

### ISSUE THREAD

**Issue by deboyblog** [lj2007331/oneinstack#51]
我今天按照官网的指南安装了最新版本（看更新日志是添加了PHP7.1的支持）
但是在新建host之后 上传war包发现怎么都不解压
之后实在无奈 看到了更新记录
为了验证是否是版本升级导致的BUG 我下载了以前服务器下的完整安装包安装
安装过程一样 软件版本选择一样
安装完成后 上传同一个war包 过了一会儿就解压了
希望这个BUG能尽快解决

**Comment by lj2007331** [comment]
请将war包放到对应网站根目录，默认/data/wwwroot/default

**Comment by deboyblog** [comment]
@lj2007331 就是说 新版的war包 位置改变了？这样的话 还有没有一个域名 多个项目都可以访问的效果？

**Comment by lj2007331** [comment]
本来定义位置就是/data/wwwroot/default ，发现很多人都放到webapps，动静分离都忽略了。不明白你说的什么意思

**Comment by deboyblog** [comment]
如果是这样我就理解了 我还以为是新版改变了存放目录 
是我没认真看 对不起 麻烦了

**Comment by lj2007331** [comment]
参考：https://oneinstack.com/question/how-to-deploy-java-application/
