### ISSUE TITLE
tomcat安装失败

### ISSUE THREAD

**Issue by lottepie** [lj2007331/oneinstack#55]
使用01-08版，在阿里云ECS的CentOS7.2下安装时，发生错误：
configure: error: Your version of OpenSSL is not compatible with this version of tcnative
Tomcat install failed, Please contact the author!
不论是使用系统自带的OpenSSL 1.0.1还是升级到1.1.0c都发生该错误。

**Comment by lj2007331** [comment]
wget mirrors.linuxeye.com/oneinstack-full.tar.gz
