### ISSUE TITLE
vhost.sh中的IP与domain匹配检测规则可能导致错误

### ISSUE THREAD

**Issue by an0sunshy** [lj2007331/oneinstack#60]
多IP主机调用get_public_ipaddr.py只可获得单个公网IP
从而导致添加的主机域名如果指向该主机上其余IP会获得错误提示

假设oneinstack都在服务器上使用
ifconfig | perl -nle 's/dr:(\S+)/print $1/e'
可获得所有公网IP但需要过滤127.0.0.*

不知是否有更好的办法

**Comment by lj2007331** [comment]
有些供应商公网ip不在ifconfig里面
