### ISSUE TITLE
Strongly adviced to add auto-config of Apache and Tomcat.

### ISSUE THREAD

**Issue by beckno9** [lj2007331/oneinstack#65]
I strongly advice to add the auto configuration of Apache 2.4 and Tomcat 8, Apache 2.4 handles HTML and PHP, all the JSP files handles by Tomcat, I think maybe a mod_jk is required, but seem  it's hard to configurate it by users themselves( I am one of these guys which wants the server can deal with PHP and JSP at the same time ).  
I saw that OneinStack package can auto configurate Nginx and Tomcat, but Nginx rewrite sucks, so this is a problem when YOU want to realize the automatic configuration of Apache + Tomcat + JDK + PHP + MySQL, I am waiting for your awnser!

**Comment by beckno9** [comment]
Also if possible, why not add the auto configuration for the Node.js and Ruby on Rails server environment? @lj2007331

**Comment by lj2007331** [comment]
Try: Nginx+Tomcat + JDK  + PHP + MySQL
