### ISSUE TITLE
Percona安装以后无法登录phpmyadmin 5.6/5.7均不行

### ISSUE THREAD

**Issue by likeclub** [lj2007331/oneinstack#66]
Percona安装以后无法登录phpmyadmin
重启后也报错
ERROR! MySQL (Percona Server) PID file could not be found!
Starting MySQL (Percona Server).170308 18:46:54 mysqld_safe The file /usr/local/Percona-Server-5.6.35-rel80.0-Linux.x86_64.ssl101/bin/mysqld
does not exist or is not executable. Please cd to the mysql installation
directory and restart this script from there as follows:
./bin/mysqld_safe&
See http://dev.mysql.com/doc/mysql/en/mysqld-safe.html for more information
ERROR! The server quit without updating PID file (/data/percona/mysql.pid).

**Comment by lj2007331** [comment]
这个问题应该修复了，percona没有启动成功导致
