### ISSUE TITLE
instructions and commands for wordpress https

### ISSUE THREAD

**Issue by johnfelipe** [lj2007331/oneinstack#71]
Hi bro i need perfect commands for install ssl to wordpress multisite instance
Stay alert

**Comment by lj2007331** [comment]
vhost.sh SSL choice 'y'

**Comment by johnfelipe** [comment]
But in WordPress is not working

**Comment by johnfelipe** [comment]
bro is not working in wordpress using Wildcard SSL provided by godaddy

**Comment by lj2007331** [comment]
eplacing the self-signed certificate.
service nginx reload

**Comment by meladelio** [comment]
hello, someone to give advice on running wp multisite with subdomain? I have set "*" in dns and set the WordPress as usual but subdomains don't show up, they don't exist. I have looked for Server alias "*" directive in apache config and added where missing but nothing changed. It works for subdirectory. Thank you in advance.
