### ISSUE TITLE
404 Not Found|| http://mirrors.linuxeye.com/apache/httpd/nghttp2-1.21.0.tar.gz

### ISSUE THREAD

**Issue by iboxtech** [lj2007331/oneinstack#73]
Download openSSL...
[openssl-1.0.2k.tar.gz] found
Download pcre...
[pcre-8.40.tar.gz] found
Download apache 2.4...
[apr-1.5.2.tar.gz] found
[apr-util-1.5.4.tar.gz] found
--2017-04-17 22:34:48--  http://mirrors.linuxeye.com/apache/httpd/nghttp2-1.21.0.tar.gz
Resolving mirrors.linuxeye.com (mirrors.linuxeye.com)... 47.88.49.186, 45.79.75.217
Connecting to mirrors.linuxeye.com (mirrors.linuxeye.com)|47.88.49.186|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-04-17 22:34:48 ERROR 404: Not Found.

nghttp2-1.21.0.tar.gz download failed, Please contact the author! 
[httpd-2.4.25.tar.gz] found
Killed
PHP common...
[libiconv-1.15.tar.gz] found

**Comment by lj2007331** [comment]
Thx!
