### ISSUE TITLE
可以添加支持 Caddy 吗？

### ISSUE THREAD

**Issue by tsunamilx** [lj2007331/oneinstack#75]
https://github.com/mholt/caddy

**Comment by baoang** [comment]
这个服务器功能是不错，但是目前直接用于生产环境可能还是极少数。
我觉得加这个服务器不如尝试OpenLiteSpeed这款，跟Apache的配置几乎通用，直接能读Apache的配置档，并且资源占用和效率可比肩Nginx

另外，Nginx官方现在有一款叫Unit的产品，觉得未来的空间还不小，直接可以取代类似php-fpm这样的环境了。

**Comment by lj2007331** [comment]
暂时不考虑
