### ISSUE TITLE
设置 pureftpd 特定路径 出错 

### ISSUE THREAD

**Issue by holyen** [lj2007331/oneinstack#76]
我设置的不是默认路径 ,/root/blog/
连接时报错 显示
Could not retrieve file listing for “/”.
Error -130: remote directory listing failed
默认路径是正常的,如何解决

**Comment by lj2007331** [comment]
默认ftp就是一般用户权限www，定位仅是上传网站代码用的
如果是其它目录建议直接用winscp root ssh账号登陆
