### ISSUE TITLE
证书安装成功，可是绑定域名出现错误

### ISSUE THREAD

**Issue by YouBubedu** [lj2007331/oneinstack#77]
在使用./addons.sh命令安装SSL证书后，显示Let’s Encrypt client installed successfully! 
可是在./vhost.sh添加域名和网站时就会报错
An unexpected error occurred:
AttributeError: 'tuple' object has no attribute 'add'
Please see the logfile '/tmp/tmp8wiI2y' for more details.
Error: Let's Encrypt SSL certificate installation failed! 
这是什么问题？该怎么解决呢？
有没有和我遇到同样问题的人？

**Comment by lj2007331** [comment]
参考：https://oneinstack.com/question/5673/

**Comment by YouBubedu** [comment]
谢谢侬
