### ISSUE TITLE
mysql无法升级5.7.18

### ISSUE THREAD

**Issue by karllo** [lj2007331/oneinstack#78]
我使用的是阿里云镜像的oneinstack

Current MySQL Version: 5.6.36

Please input upgrade MySQL Version(example: 5.6.36): 5.7.18
input error! Please only input '5.6.xx'

**Comment by lj2007331** [comment]
不支持挂大版本升级。。

**Comment by karllo** [comment]
可以开辟支持5.7.18的么？大大

**Comment by karllo** [comment]
或者有什么办法重新安装mysql5.7.18?

**Comment by lj2007331** [comment]
./uninstall.sh db 卸载数据库，注意备份
./install.sh 数据库选择y，选择5.7版本即可

**Comment by karllo** [comment]
谢谢，安装上了，可是用tz.php中的MySQL数据库连接检测，却无法连接，phpmyadmin可以打开数据库的，怎么破？

**Comment by karllo** [comment]
HTTP ERROR 500

**Comment by lj2007331** [comment]
@karllo tz请忽略，老版本 有问题。

**Comment by karllo** [comment]
https://www.karlw.cn/

可是还是无法打开这个网站额，用的是laravel,windows2016 64位版本下，同样的布置可以打开的
nginx，php,mysql的配置文件在哪里？

还有如果我升级nginx到1.13.0版本的话，reload以后tz的版本显示仍然是1.12.0，怎么破？

**Comment by karllo** [comment]
再问一个centos的问题，google我搜不到

就是.env等文件在ftp上显示不了，用的是winscp连接的，这个怎么弄？

**Comment by slince** [comment]
@lj2007331   好像并没有 `install.sh ` 文件 。
