### ISSUE TITLE
nginx proxy.conf 端口传递配置缺失的issue

### ISSUE THREAD

**Issue by cnyyk** [lj2007331/oneinstack#80]
在 `/usr/local/tengine/conf/proxy.conf` 配置文件中，有一行用来传递当前服务器名称，如下：

`proxy_set_header Host $host;`

大多数情况下不会有问题，apache 那边默认处理的是 80 端口。

但极少数应用可能部署在非80端口的情况。
我最近就遇到了，业务部署在 `http://www.abc.com:9527/`，然后怎么搞都会导致后台处理自动跳转到 `http://www.abc.com/`，端口丢失。

跟踪了代码及本地的 mamp pro 环境，一切都 OK。
最后仔细看了服务器配置，发现是上面那句话的问题，于是修复：

`proxy_set_header Host $host:$server_port;`

这样就好了，就可以把业务域名的端口号一起传递过去了。

建议下个版本发布的时候，默认将这个端口传递到 apache／php 那边，否则不知又有多少人要踏进这个坑。。。

**Comment by lj2007331** [comment]
已经修正，谢谢反馈
https://github.com/lj2007331/oneinstack/commit/065234cc40692bf2a549fc23a47196fe2824ef6c
