### ISSUE TITLE
Arch要用的话,会很麻烦吗?

### ISSUE THREAD

**Issue by TIL-MICE** [lj2007331/oneinstack#81]
本地一个Ubuntu一个Arch,Ubuntu为生产系统,想用arch作为测试系统,何解?

**Comment by ivmm** [comment]
一键包主要应用于生产环境，所以一般不会考虑 Arch。

反正都已经能折腾安装好 Arch 了，不如自行再研究搭建 LNMP 环境

**Comment by TIL-MICE** [comment]
嗯，也是，只是对脚本比较好奇，感觉挺方便的，遇到麻烦再来提issue

**Comment by ivmm** [comment]
全部都读一遍，肯定大致都知道了
