### ISSUE TITLE
Let's Encrypt是自动续签的么？

### ISSUE THREAD

**Issue by karllo** [lj2007331/oneinstack#84]
因为默认只是三个月，以后还得重新生成证书

**Comment by lj2007331** [comment]
crontab -l 里面有自动续签，或者手工执行强制续签命令：
`/usr/local/python/bin/certbot renew --force-renew --renew-hook "/etc/init.d/nginx reload"`

**Comment by riverai** [comment]
检查了发现cerbot文件大小是0KB,难怪续期不成功。
