### ISSUE TITLE
Let'sEncrypt常年姨妈

### ISSUE THREAD

**Issue by minmemory** [lj2007331/oneinstack#88]
安装上去首先第一次会出现
`An unexpected error occurred:

UnicodeEncodeError: 'ascii' codec can't encode character u'\ufeff' in position 188: ordinal not in range(128)
Please see the logfiles in /var/log/letsencrypt for more details. 
       
Error: Let's Encrypt SSL certificate installation failed! `                 
人工创建/usr/local/python/lib/python2.7/site-packages/sitecustomize.py 设定了utf8后，变成以下错误

**Comment by minmemory** [comment]
`Failed authorization procedure. iot-gz.cn (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://iot-gz.cn/.well-known/acme-challenge/3L2MpcJ807DY_dKtJKSecB5h8yLpHw_KVZ7WoCSzWiQ: “(!DOCTYPE html)
(html)
(head lang=”en”)
(meta charset=”UTF-8″)
(meta http-equiv=”X-UA-Compatible” content=”IE=edge,chro”, http://www.iot-gz.cn (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://www.iot-gz.cn/.well-known/acme-challenge/FuQSJslzw1z_kdbxGXoFhqTMXxw9qVIin-1rY-224mA: (!DOCTYPE html)
(html)
(head lang=”en”)
(meta charset=”UTF-8″)
(meta http-equiv=”X-UA-Compatible” content=”IE=edge,chro
Error: Let’s Encrypt SSL certificate installation failed! `

**Comment by lj2007331** [comment]
网站根目录里面的.well-known验证文件干掉了吗？
