### ISSUE TITLE
php编译时建议增加参数--with-config-file-scan-dir=/usr/local/php/etc/conf.d

### ISSUE THREAD

**Issue by wkii** [lj2007331/oneinstack#9]
建议增加此参数。
这样无论是安装了memcached，还是mongo等扩展，其配置可以放在/usr/local/php/etc/conf.d中。
只需要看这个目录就知道有那些扩展了。

话说这个参数是从brew的php编译参数中学来的。

然后可以这样：
# 配置载入扩展
mkdir -p /usr/local/php/etc/conf.d
cat > /usr/local/php/etc/conf.d/ext-memcached.ini<<EOF
[memcached]
extension = "memcached.so"
EOF

cat > /usr/local/php/etc/conf.d/ext-imagick.ini<<EOF
[imagick]
extension = "imagick.so"
EOF

不必去费力的修改php.ini

**Comment by lj2007331** [comment]
nice，后面慢慢加上

**Comment by lj2007331** [comment]
已提交并更新！！

**Comment by wenpeng** [comment]
Xdebug 和 composer 一起使用有问题，这个时候会复制出来一份 php-cli.ini，那么问题来了，php-cli.ini 也会去读这个 php.d，这个时候就尴尬了

**Comment by davidtall** [comment]
> Xdebug 和 composer 一起使用有问题，这个时候会复制出来一份 php-cli.ini，那么问题来了，php-cli.ini 也会去读这个 php.d，这个时候就尴尬了

我也遇到了这个问，不知道如果解决好
