### ISSUE TITLE
centos 6.8 安装二进制mysql报错了

### ISSUE THREAD

**Issue by cliff363825** [lj2007331/oneinstack#92]
报错信息：error while loading shared libraries: libnuma.so.1: cannot open shared object file: No such file or directory

我看了下 include/check_sw.sh 发现安装依赖包里面有numactl-libs，但实际手动去yum install numactl-libs的时候，却显示No package numactl-libs available.

我是通过 yum install numactl 之后，重新安装mysql就可以了。

附：
![qq 20170731182752](https://user-images.githubusercontent.com/7607892/28774207-1f7cefbe-761f-11e7-8235-aa839886ec2f.png)

**Comment by lj2007331** [comment]
谢谢反馈，已经提交：https://github.com/lj2007331/oneinstack/commit/5676d769e6bfdb1131e62702c91b7075ede9266f
